org: jaddielorzano
service: awsnodetraining-cjr

frameworkVersion: '3'

provider:
  name: aws
  stage: dev
  iam: 
    role: arn:aws:iam::702954692849:role/awsnodetraining-dev-role
  runtime: nodejs16.x
  region: ap-southeast-1
  deploymentMethod: direct
  deploymentBucket:
    name: awsnodejstraining
    versioning: true
  deploymentPrefix: cris-jaddie-rodel
  endpointType: REGIONAL
  environment:
    tableName: ${self:custom.flexBenTableName}

custom:
  flexBenTableName: flexben-api-cjr

functions:
  Flexben:
    handler: index.api
    name: awsnodetraining-${sls:stage}-flexben-api-cjr
    description: Lambda Function for FlexBen API for AWS NodeJS Training by Cris, Jaddie, and Rodel